### ISSUE TITLE
[公司] Meta

### ISSUE THREAD

**Issue by ylqi007** [ylqi007/LeetCode#28]
- [x] [314. Binary Tree Vertical Order Traversal](https://leetcode.com/problems/binary-tree-vertical-order-traversal) [BFS, ArrayDeque]
  - [x] [102. Binary Tree Level Order Traversal](https://leetcode.com/problems/binary-tree-level-order-traversal/) [BFS]
- [x] 🟩🌟 [408. Valid Word Abbreviation](https://leetcode.com/problems/valid-word-abbreviation) [**Two Pointers**, ⚠️注意分析]
- [x] [1249. Minimum Remove to Make Valid Parenthes](https://leetcode.com/problems/minimum-remove-to-make-valid-parentheses) [Stack, **ArrayDeque**]
  - [x] [1963. Minimum Number of Swaps to Make the String Balanced](https://leetcode.com/problems/minimum-number-of-swaps-to-make-the-string-balanced/)
  - [ ] [2116. Check if a Parentheses String Can Be Valid](https://leetcode.com/problems/check-if-a-parentheses-string-can-be-valid/)
- [x] [339. Nested List Weight Sum](https://leetcode.com/problems/nested-list-weight-sum) [DFS]
  - [x] [364. Nested List Weight Sum II](https://leetcode.com/problems/nested-list-weight-sum-ii/)
  - [ ] 🟥 [565. Array Nesting](https://leetcode.com/problems/array-nesting/) [Apple的]
  - [ ] [690. Employee Importance](https://leetcode.com/problems/employee-importance/) [DFS, BFS]
- [x] [1650. Lowest Common Ancestor of a Binary Tree III](https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree-iii)
  - [x] [235. Lowest Common Ancestor of a Binary Search Tree](https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/) [Recursion递归, **Iteration迭代**]
  - [x] [236. Lowest Common Ancestor of a Binary Tree](https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/) [前提p != q，p and q will exist in the tree.]
  - [x] [1644. Lowest Common Ancestor of a Binary Tree II](https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree-ii/)
  - [x] 🟨🌟[1650. Lowest Common Ancestor of a Binary Tree III](https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree-iii/) [其实就是两个LinkedList的交叉点]
  - [x] 🟨🌟[1676. Lowest Common Ancestor of a Binary Tree IV](https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree-iv/)
- [ ] 🟩🌟[680. Valid Palindrome II](https://leetcode.com/problems/valid-palindrome-ii) [注意复杂度分析O(N)]
  - [ ] [125. Valid Palindrome](https://leetcode.com/problems/valid-palindrome/)
- [ ] [1570. Dot Product of Two Sparse Vectors](https://leetcode.com/problems/dot-product-of-two-sparse-vectors)
- [ ] [1762. Buildings With an Ocean View](https://leetcode.com/problems/buildings-with-an-ocean-view)
- [ ] [528. Random Pick with Weight](https://leetcode.com/problems/random-pick-with-weight)
- [ ] [227. Basic Calculator II](https://leetcode.com/problems/basic-calculator-ii)
- [ ] [215. Kth Largest Element in an Array](https://leetcode.com/problems/kth-largest-element-in-an-array)
- [ ] [938. Range Sum of BST](https://leetcode.com/problems/range-sum-of-bst)
- [ ] [71. Simplify Path](https://leetcode.com/problems/simplify-path)
- [ ] [691. Stickers to Spell Word](https://leetcode.com/problems/stickers-to-spell-word)
- [ ] [236. Lowest Common Ancestor of a Binary Tree](https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree)
- [ ] [346. Moving Average from Data Stream](https://leetcode.com/problems/moving-average-from-data-stream)
- [ ] [791. Custom Sort String](https://leetcode.com/problems/custom-sort-string)
- [ ] [1091. Shortest Path in Binary Matrix](https://leetcode.com/problems/shortest-path-in-binary-matrix)
- [ ] [426. Convert Binary Search Tree to Sorted Doubly Linked List](https://leetcode.com/problems/convert-binary-search-tree-to-sorted-doubly-linked-list)
- [ ] [827. Making A Large Island](https://leetcode.com/problems/making-a-large-island)
- [ ] [921. Minimum Add to Make Parentheses Valid](https://leetcode.com/problems/minimum-add-to-make-parentheses-valid)
- [x] [50. Pow(x, n)](https://leetcode.com/problems/powx-n)
  - [ ] [69. Sqrt(x)](https://leetcode.com/problems/sqrtx/)
- [ ] [973. K Closest Points to Origin](https://leetcode.com/problems/k-closest-points-to-origin)
- [ ] [162. Find Peak Element](https://leetcode.com/problems/find-peak-element)
- [ ] [560. Subarray Sum Equals K](https://leetcode.com/problems/subarray-sum-equals-k)
- [ ] [199. Binary Tree Right Side View](https://leetcode.com/problems/binary-tree-right-side-view)
- [ ] [708. Insert into a Sorted Circular Linked List](https://leetcode.com/problems/insert-into-a-sorted-circular-linked-list)
- [x] [138. Copy List with Random Pointer](https://leetcode.com/problems/copy-list-with-random-pointer)
- [x] 🟨🌟 [249. Group Shifted Strings](https://leetcode.com/problems/group-shifted-strings)
  - [ ] [49. Group Anagrams](https://leetcode.com/problems/group-anagrams/)
  - [ ] [2744. Find Maximum Number of String Pairs](https://leetcode.com/problems/find-maximum-number-of-string-pairs/)
- [ ] 🟥🌟[65. Valid Number](https://leetcode.com/problems/valid-number)
  - [ ] [8. String to Integer (atoi)](https://leetcode.com/problems/string-to-integer-atoi/)
- [x] [129. Sum Root to Leaf Numbers](https://leetcode.com/problems/sum-root-to-leaf-numbers)
  - [ ] [112. Path Sum](https://leetcode.com/problems/path-sum/)
  - [ ] [124. Binary Tree Maximum Path Sum](https://leetcode.com/problems/binary-tree-maximum-path-sum/)
  - [ ] [988. Smallest String Starting From Leaf](https://leetcode.com/problems/smallest-string-starting-from-leaf/)
- [x] [543. Diameter of Binary Tree](https://leetcode.com/problems/diameter-of-binary-tree)
  - [ ] [1522. Diameter of N-Ary Tree](https://leetcode.com/problems/diameter-of-n-ary-tree/)
  - [ ] 🟥[2246. Longest Path With Different Adjacent Characters](https://leetcode.com/problems/longest-path-with-different-adjacent-characters/)
- [x] 🟨🌟[986. Interval List Intersections](https://leetcode.com/problems/interval-list-intersections)
  - [x] [56. Merge Intervals](https://leetcode.com/problems/merge-intervals)
  - [x] [88. Merge Sorted Array](https://leetcode.com/problems/merge-sorted-array/)
  - [x] [759. Employee Free Time](https://leetcode.com/problems/employee-free-time/)
  - [x] [2410. Maximum Matching of Players With Trainers](https://leetcode.com/problems/maximum-matching-of-players-with-trainers/)
- [x] 🟨🌟[56. Merge Intervals](https://leetcode.com/problems/merge-intervals)
- [x] [146. LRU Cache](https://leetcode.com/problems/lru-cache)
  - [ ] [460. LFU Cache](https://leetcode.com/problems/lfu-cache/)
  - [ ] [588. Design In-Memory File System](https://leetcode.com/problems/design-in-memory-file-system/)
  - [ ] [604. Design Compressed String Iterator](https://leetcode.com/problems/design-compressed-string-iterator/)
  - [ ] [1756. Design Most Recently Used Queue](https://leetcode.com/problems/design-most-recently-used-queue/)
- [x] [398. Random Pick Index](https://leetcode.com/problems/random-pick-index)
  - [ ] [382. Linked List Random Node](https://leetcode.com/problems/linked-list-random-node/)
  - [ ] [710. Random Pick with Blacklist](https://leetcode.com/problems/random-pick-with-blacklist/)
  - [ ] [528. Random Pick with Weight](https://leetcode.com/problems/random-pick-with-weight/)
- [x] [670. Maximum Swap](https://leetcode.com/problems/maximum-swap)
- [x] 🟨🌟[498. Diagonal Traverse](https://leetcode.com/problems/diagonal-traverse)
- [x] [88. Merge Sorted Array](https://leetcode.com/problems/merge-sorted-array)
- [ ] 🟨🌟[31. Next Permutation](https://leetcode.com/problems/next-permutation)
- [ ] [301. Remove Invalid Parentheses](https://leetcode.com/problems/remove-invalid-parentheses)
  - [ ] [20. Valid Parentheses](https://leetcode.com/problems/valid-parentheses/)
  - [ ] [1963. Minimum Number of Swaps to Make the String Balanced](https://leetcode.com/problems/minimum-number-of-swaps-to-make-the-string-balanced/)
- [x] 🟥🌟[317. Shortest Distance from All Buildings](https://leetcode.com/problems/shortest-distance-from-all-buildings)
  - [ ] [286. Walls and Gates](https://leetcode.com/problems/walls-and-gates/)
  - [ ] [296. Best Meeting Point](https://leetcode.com/problems/best-meeting-point/)
  - [ ] [1162. As Far from Land as Possible](https://leetcode.com/problems/as-far-from-land-as-possible/)
- [ ] 🟥🌟[987. Vertical Order Traversal of a Binary Tree](https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree)
  - [ ] [314. Binary Tree Vertical Order Traversal](https://leetcode.com/problems/binary-tree-vertical-order-traversal/description/)
- [x] [766. Toeplitz Matrix](https://leetcode.com/problems/toeplitz-matrix)
  - [ ] [422. Valid Word Square](https://leetcode.com/problems/valid-word-square/)
- [ ] [347. Top K Frequent Elements](https://leetcode.com/problems/top-k-frequent-elements)
- [ ] [23. Merge k Sorted Lists](https://leetcode.com/problems/merge-k-sorted-lists)
- [x] [125. Valid Palindrome](https://leetcode.com/problems/valid-palindrome)
- [ ] [636. Exclusive Time of Functions](https://leetcode.com/problems/exclusive-time-of-functions)
- [ ] [270. Closest Binary Search Tree Value](https://leetcode.com/problems/closest-binary-search-tree-value)
- [ ] [1868. Product of Two Run-Length Encoded Arrays](https://leetcode.com/problems/product-of-two-run-length-encoded-arrays)

**Comment by ylqi007** [comment]
面经

- [x] ✅⭐[347. Top K Frequent Elements](https://leetcode.com/problems/top-k-frequent-elements/)
  * 3开头那道题目问如果 1<k <<N(nums长度), 就是需要的k比N要少很多很多该怎么办, 我最早觉得用heap 这样space会很低 所以先写了heap,沟通follow up后感觉面试官希望用bucket sort那个方法 time ON, 于是两种方法都写了, 也dry run了
- [x] ✅⭐[215. Kth Largest Element in an Array](https://leetcode.com/problems/kth-largest-element-in-an-array/)
  * Quick Select
- [ ] [543. Diameter of Binary Tree](https://leetcode.com/problems/diameter-of-binary-tree/)
  * follow up问如果要算diameter的同时还要记录valid path 怎么办, time complexity 是多少, 只需要我说time,也说了也还是ON, 还把psedo code 的if 判断也大概写了 + dryrun
- [ ] [207. Course Schedule](https://leetcode.com/problems/course-schedule/)
- [ ] [314. Binary Tree Vertical Order Traversal](https://leetcode.com/problems/binary-tree-vertical-order-traversal/)
- [x] 🟨🌟[1249. Minimum Remove to Make Valid Parentheses](https://leetcode.com/problems/minimum-remove-to-make-valid-parentheses/)
- [ ] [983. Minimum Cost For Tickets](https://leetcode.com/problems/minimum-cost-for-tickets/)
- [x] [236. Lowest Common Ancestor of a Binary Tree](https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/)
  - [x] [235. Lowest Common Ancestor of a Binary Search Tree](https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/)
  - [x] [1644. Lowest Common Ancestor of a Binary Tree II](https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree-ii/)
  - [ ] [1676. Lowest Common Ancestor of a Binary Tree IV](https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree-iv/) [Amazon, 还没有 Meta tag]
- [ ] [121. Best Time to Buy and Sell Stock](https://leetcode.com/problems/best-time-to-buy-and-sell-stock/)
- [ ] [1197. Minimum Knight Moves](https://leetcode.com/problems/minimum-knight-moves/)
- [ ] [1091. Shortest Path in Binary Matrix](https://leetcode.com/problems/shortest-path-in-binary-matrix/)
- [x] [408. Valid Word Abbreviation](https://leetcode.com/problems/valid-word-abbreviation/)
- [ ] [252. Meeting Rooms](https://leetcode.com/problems/meeting-rooms/)
- [ ] [253. Meeting Rooms II](https://leetcode.com/problems/meeting-rooms-ii/)
- [x] 🟨🌟[56. Merge Intervals](https://leetcode.com/problems/merge-intervals/)
- [ ] Valid Palindrome
  - [x] 🟨🌟[125. Valid Palindrome](https://leetcode.com/problems/valid-palindrome/)
  - [x] 🟨🌟[680. Valid Palindrome II](https://leetcode.com/problems/valid-palindrome-ii/)
  - [x] [1216. Valid Palindrome III](https://leetcode.com/problems/valid-palindrome-iii/)
